### ISSUE TITLE
Pequeno ajuste no deployment.yaml

### ISSUE THREAD

**Issue by vini-md** [joaohudson/kubernetes-sample#1]
o arquivo `k8s.yaml` contém um pequeno errinho bem tranquilo de corrigir. Segue:

Antes: https://github.com/joaohudson/kubernetes-sample/blob/master/k8s.yaml#L62
```yaml
env:
    - name: CONFIG_VALUE
      valueFrom:
        configMapKeyRef:
          name: sample-config
          key: CONFIG_VALUE
    - name: PRIVATE_VALUE
      valueFrom:
        configMapKeyRef: <-----------
          name: sample-secret
          key: PRIVATE_VALUE
```

Depois:
```yaml
env:
    - name: CONFIG_VALUE
      valueFrom:
        configMapKeyRef:
          name: sample-config
          key: CONFIG_VALUE
    - name: PRIVATE_VALUE
      valueFrom:
        secretKeyRef: <------------
          name: sample-secret
          key: PRIVATE_VALUE
```

Ao modificar isso subiu corretamente, parabéns!
